import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


def generate_report(
    missing_df,
    percentage_df,
    outlier_df
):

    report = pd.concat(

        [

            missing_df,

            percentage_df["Missing Percentage"],

            outlier_df["Outliers"]

        ],

        axis=1

    )

    return report


def create_pdf(score, total_missing, duplicates, output_path):
    """
    Create a simple PDF summary report for the current dataset.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = PdfPages(output_path)

    fig = plt.figure(figsize=(8.5, 11))
    fig.text(0.1, 0.95, "AI Data Quality Checker", fontsize=18, weight="bold")
    fig.text(0.1, 0.88, f"Quality Score: {score}%")
    fig.text(0.1, 0.82, f"Total Missing Values: {total_missing}")
    fig.text(0.1, 0.76, f"Duplicate Rows: {duplicates}")
    fig.text(0.1, 0.68, "This report was generated by the AI Data Quality Checker.")

    pdf.savefig(fig)
    plt.close(fig)
    pdf.close()

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph
)
from reportlab.lib.styles import getSampleStyleSheet


def create_pdf(
    score,
    missing,
    duplicates,
    filename
):

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(filename)

    elements = []

    elements.append(
        Paragraph(
            "<b>AI Data Quality Report</b>",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            f"Quality Score: {score}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"Missing Values: {missing}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"Duplicates: {duplicates}",
            styles["Normal"]
        )
    )

    pdf.build(elements)